# name: ci

# on:
#   push:

# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#       -
#         name: Set up QEMU
#         uses: docker/setup-qemu-action@v3
#       -
#         name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3
#       -
#         name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: am2501
#           password: Yakei39ra
#       -
#         name: Build and push
#         uses: docker/build-push-action@v6
#         with:
#           file: Dockerfile
#           push: true
#           tags: sa-k-ra/stady_test:latest

name: Pentest with Docker

on:
  push:
    branches:
      - main

jobs:
  pentest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Kali Linux Docker Container
        uses: docker://kalilinux/kali-rolling
        with:
          args: |
            bash -c 
            apt install -y kali-linux-default
            nmap -sV -T4 127.0.0.1:8000
